# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `omniauth-naver` gem.
# Please instead update this file by running `bin/tapioca gem omniauth-naver`.


# source://omniauth-naver//lib/omniauth/strategies/naver.rb#3
module OmniAuth
  class << self
    # source://omniauth/2.1.3/lib/omniauth.rb#134
    def config; end

    # source://omniauth/2.1.3/lib/omniauth.rb#138
    def configure; end

    # source://omniauth/2.1.3/lib/omniauth.rb#142
    def logger; end

    # source://omniauth/2.1.3/lib/omniauth.rb#146
    def mock_auth_for(provider); end

    # source://omniauth/2.1.3/lib/omniauth.rb#24
    def strategies; end
  end
end

# source://omniauth-naver//lib/omniauth/strategies/naver.rb#4
module OmniAuth::Strategies; end

# source://omniauth-naver//lib/omniauth/strategies/naver.rb#5
class OmniAuth::Strategies::Naver < ::OmniAuth::Strategies::OAuth2
  private

  # source://omniauth-naver//lib/omniauth/strategies/naver.rb#32
  def gender; end

  # source://omniauth-naver//lib/omniauth/strategies/naver.rb#38
  def image; end

  # source://omniauth-naver//lib/omniauth/strategies/naver.rb#43
  def raw_info; end

  # source://omniauth-naver//lib/omniauth/strategies/naver.rb#47
  def raw_properties; end
end

# source://omniauth-naver//lib/omniauth-naver/version.rb#1
module Omniauth; end

# source://omniauth-naver//lib/omniauth-naver/version.rb#2
module Omniauth::Naver; end

# source://omniauth-naver//lib/omniauth-naver/version.rb#3
Omniauth::Naver::VERSION = T.let(T.unsafe(nil), String)
