# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PeriodicJobs::GenerateLlmBillSummaryPeriodicJob`.
# Please instead update this file by running `bin/tapioca dsl PeriodicJobs::GenerateLlmBillSummaryPeriodicJob`.


class PeriodicJobs::GenerateLlmBillSummaryPeriodicJob
  class << self
    sig do
      params(
        block: T.nilable(T.proc.params(job: PeriodicJobs::GenerateLlmBillSummaryPeriodicJob).void)
      ).returns(T.any(PeriodicJobs::GenerateLlmBillSummaryPeriodicJob, FalseClass))
    end
    def perform_later(&block); end

    sig { void }
    def perform_now; end
  end
end
